### ISSUE TITLE
PyTorch version and nan in o_output 

### ISSUE THREAD

**Issue by sunlightsgy** [yaohungt/Gated-Spatio-Temporal-Energy-Graph#1]
Thanks for nice code!

However, is the code be checked in pytorch 1.0? I see some v0.31 style codes, and in `train.py` line 154, `losses.update(loss.data[0], input.size(0))` should be `losses.update(loss.data.item(), input.size(0))`?

Besides, I follow the instruction as required in README, but I got some tensors with nan values in `o_output` in `train.py`, line 139. Therefore, I got errors. Do you have any idea about this?

**Comment by yaohungt** [comment]
Hi,


I check the version and it is pytorch v1.0. I may have some obsolete code
that is from older version. And I only encounter nan value once, which is
like in the probability ~ 1/100. I'm not sure how it happens. Besides, I
think running this experiment requires at least four GPUs, I'm not sure if
there's any issue with it.

Best,
Hubert

**Comment by sunlightsgy** [comment]
The `loss.data[0]` will raise an error after pytorch 0.4. And almost every time I encounter nan value.
I have four GPUs with 12GB memory. I adopt all the default settings, except for modifing the `losses.update(loss.data[0], input.size(0))` and the data location in `GSTEG.py`.

**Comment by yaohungt** [comment]
Hi,

I checked again, and I'm using pytorch 1.0.1. Also, I test the code several
times before uploading the code, but I have not encoutered nan values.

Best,
Hubert

**Comment by sunlightsgy** [comment]
Well I'm using pytorch 1.0.1 also.
What's your cuda version?

**Comment by yaohungt** [comment]
Hi, sorry that I double check the machine I'm running the experiment. 

The version of pytorch is 0.4, and the cuda is v7.5. It seems to be obsolete.

However, I have this code running also on a machine with cuda v10.0, and do the .item() stuff and it seems to work fine.

**Comment by sunlightsgy** [comment]
Ok...I am in cuda v9.0. 
I'll try some different environments later and be back here if it cannot work...

**Comment by sunlightsgy** [comment]
This time I use PyTorch 0.4.1, do the .item(), and have 10 GPUs. It seems everything goes well.
I guess the error above may be caused by lacking of enough GPUs (or memory) earlier.

Thank you!
