### ISSUE TITLE
Will the code for VidVRD be released?

### ISSUE THREAD

**Issue by sunlightsgy** [yaohungt/Gated-Spatio-Temporal-Energy-Graph#2]
This repo is the code for Charades activity recognition. Will the code for VidVRD relation detection be released? Pre-Reasoning Modules are different in the two settings.

**Comment by yaohungt** [comment]
We have no plan releasing the code for VidVRD for now. 
You may refer 

https://github.com/xdshang/VidVRD-helper

for the pre-reasoning modules used for VidVRD.
