### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by sanfordhsu** [yaohungt/Gated-Spatio-Temporal-Energy-Graph#3]
Thanks for your share.
when I run as your README, got the following error, do u know how to fix it? Thanks again!
 
![00](https://user-images.githubusercontent.com/35886298/58238380-b7d1b700-7d79-11e9-88bf-493f2e3be67c.png)

**Comment by yaohungt** [comment]
It seems like you do not run prediction on the entire set of videos. The groundtruth contains entire set of videos, and thus you may need to run all of them to run eval_visual_relation function.

You can modify line 72 in utils/__init__.py to block the vedio id which is not in your prediction results.

**Comment by sanfordhsu** [comment]
> It seems like you do not run prediction on the entire set of videos. The groundtruth contains entire set of videos, and thus you may need to run all of them to run eval_visual_relation function.
> 
> You can modify line 72 in utils/**init**.py to block the vedio id which is not in your prediction results.

But I did not change the videos file for prediction. I wonder if the problem occurred because I did not split the videos into training and validation file?

**Comment by yaohungt** [comment]
I don’t think it will make a difference. Are you sure that you have set the right path for data?

**Comment by sanfordhsu** [comment]
> I don’t think it will make a difference. Are you sure that you have set the right path for data?
> […](#)
> sanfordhsu ***@***.***> 於 2019年5月24日 上午12:44 寫道： It seems like you do not run prediction on the entire set of videos. The groundtruth contains entire set of videos, and thus you may need to run all of them to run eval_visual_relation function. You can modify line 72 in utils/init.py to block the vedio id which is not in your prediction results. But I did not change the videos file for prediction. I wonder if the problem occurred because I did not split the videos into training and validation file? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Well, I try again and change the path format, and it works, thanks. I' ll close issue.
