### ISSUE TITLE
Process gets killed during data preparation

### ISSUE THREAD

**Issue by CaesarPan** [yaohungt/Gated-Spatio-Temporal-Energy-Graph#6]
Thanks for sharing the code!

Seems that every time I run the code it'll get killed during the data preparation (`self.data = cache(cachename)(self.prepare)(rgb_root, self.labels, split)`) with the following prompt message:

```
...
5600 ./Charades_v1_rgb/8MIK9
5700 ./Charades_v1_rgb/SLIH4
5800 ./Charades_v1_rgb/JX8SN
5900 ./Charades_v1_rgb/GR5N6
6000 ./Charades_v1_rgb/8BBX0
6100 ./Charades_v1_rgb/RRDAM
6200 ./Charades_v1_rgb/MYZLT
6300 ./Charades_v1_rgb/91YZH
6400 ./Charades_v1_rgb/Q1JBR
6500 ./Charades_v1_rgb/DK59J
6600 ./Charades_v1_rgb/ZG8KO
Killed
```
`...` indicates lines showing processed videos before. Any insights on why this is happening?

Thanks!

**Comment by yaohungt** [comment]
I remembered that I've seen this issue before. But later on, I have never faced this issue. My solution is just changing to another machine, and it magically worked out.....
