### ISSUE TITLE
after dataset loader, the image batch size is (25,3,10,244,244).  the value seems in (-1,1), not in (0,1).  

### ISSUE THREAD

**Issue by 321hallelujah** [yaohungt/Gated-Spatio-Temporal-Energy-Graph#8]
could  a single image ( 3, 224, 224) have negative value ?  what that means? 
thanks!

code line "        for i, (input, s_target, o_target, v_target, meta) in enumerate(part(loader)): "
ipdb> print(input)
tensor([[[[[-0.3255, -0.3176, -0.3176,  ...,  0.0196,  0.0196,  0.0118],
           [-0.3176, -0.3255, -0.3255,  ...,  0.0118,  0.0039, -0.0039],
           [-0.3333, -0.3490, -0.3490,  ..., -0.0353, -0.0588, -0.0353],
           ...,
           [ 0.0431,  0.0431,  0.0431,  ...,  0.3333,  0.3412,  0.3333],
           [ 0.0431,  0.0431,  0.0431,  ...,  0.3333,  0.3412,  0.3333],
           [ 0.0510,  0.0431,  0.0431,  ...,  0.3412,  0.3412,  0.3098]],

          [[-0.3255, -0.3255, -0.3255,  ..., -0.2157, -0.1843, -0.1373],
           [-0.3255, -0.3333, -0.3333,  ..., -0.2078, -0.1843, -0.1451],
           [-0.3490, -0.3490, -0.3490,  ..., -0.1843, -0.1608, -0.1451],
           ...,
           [ 0.0353,  0.0431,  0.0431,  ...,  0.3333,  0.3412,  0.3333],
           [ 0.0353,  0.0431,  0.0431,  ...,  0.3333,  0.3412,  0.3333],
           [ 0.0431,  0.0431,  0.0431,  ...,  0.3412,  0.3412,  0.3176]],

          [[-0.3412, -0.3255, -0.3255,  ..., -0.1922, -0.1843, -0.1451],
           [-0.3490, -0.3333, -0.3333,  ..., -0.1922, -0.1765, -0.1373],
           [-0.3725, -0.3490, -0.3490,  ..., -0.1843, -0.1686, -0.1451],
           ...,
           [ 0.0353,  0.0431,  0.0431,  ...,  0.3255,  0.3333,  0.3333],
           [ 0.0353,  0.0431,  0.0431,  ...,  0.3333,  0.3333,  0.3333],
           [ 0.0431,  0.0431,  0.0431,  ...,  0.3412,  0.3412,  0.3176]],

          ...,

          [[-0.3490, -0.3333, -0.3333,  ..., -0.1216, -0.1294, -0.1451],
           [-0.3490, -0.3333, -0.3333,  ..., -0.1608, -0.1529, -0.1608],
           [-0.3647, -0.3412, -0.3412,  ..., -0.1922, -0.1922, -0.1922],
           ...,
           [ 0.0431,  0.0431,  0.0431,  ...,  0.3255,  0.3333,  0.3098],
           [ 0.0431,  0.0431,  0.0431,  ...,  0.3333,  0.3333,  0.3098],
           [ 0.0510,  0.0510,  0.0510,  ...,  0.3333,  0.3333,  0.3020]],

          [[-0.3490, -0.3333, -0.3333,  ..., -0.1843, -0.1922, -0.1765],
           [-0.3490, -0.3333, -0.3333,  ..., -0.2000, -0.2000, -0.2000],
           [-0.3569, -0.3490, -0.3490,  ..., -0.2235, -0.2078, -0.2157],
           ...,
           [ 0.0353,  0.0431,  0.0431,  ...,  0.3255,  0.3333,  0.3098],
           [ 0.0353,  0.0431,  0.0431,  ...,  0.3333,  0.3333,  0.3098],
           [ 0.0431,  0.0431,  0.0431,  ...,  0.3333,  0.3333,  0.3020]],

          [[-0.3490, -0.3333, -0.3333,  ..., -0.2706, -0.2392, -0.1922],
           [-0.3490, -0.3333, -0.3333,  ..., -0.2706, -0.2471, -0.1922],
           [-0.3569, -0.3490, -0.3490,  ..., -0.2941, -0.2706, -0.2000],
           ...,
           [ 0.0353,  0.0431,  0.0431,  ...,  0.3255,  0.3333,  0.3176],
           [ 0.0353,  0.0431,  0.0431,  ...,  0.3333,  0.3333,  0.3176],
           [ 0.0431,  0.0431,  0.0431,  ...,  0.3333,  0.3333,  0.3098]]],

         [[[-0.2627, -0.2706, -0.2706,  ...,  0.0980,  0.0902,  0.0745],
           [-0.2549, -0.2784, -0.2784,  ...,  0.0902,  0.0745,  0.0431],
           [-0.2706, -0.3020, -0.3020,  ...,  0.0275,  0.0118,  0.0118],
           ...,
           [ 0.0667,  0.0588,  0.0588,  ...,  0.3490,  0.3569,  0.3647],
           [ 0.0667,  0.0588,  0.0588,  ...,  0.3490,  0.3569,  0.3647],
           [ 0.0745,  0.0588,  0.0588,  ...,  0.3569,  0.3569,  0.3412]],

          [[-0.2627, -0.2784, -0.2784,  ..., -0.0980, -0.0824, -0.0510],
           [-0.2627, -0.2863, -0.2863,  ..., -0.0902, -0.0824, -0.0510],
           [-0.2863, -0.3020, -0.3020,  ..., -0.0824, -0.0588, -0.0588],
           ...,
           [ 0.0588,  0.0588,  0.0588,  ...,  0.3490,  0.3569,  0.3647],
           [ 0.0588,  0.0588,  0.0588,  ...,  0.3490,  0.3569,  0.3647],
           [ 0.0667,  0.0588,  0.0588,  ...,  0.3569,  0.3569,  0.3490]],

          [[-0.2549, -0.2784, -0.2784,  ..., -0.0824, -0.0745, -0.0431],
           [-0.2627, -0.2863, -0.2863,  ..., -0.0902, -0.0824, -0.0510],
           [-0.2863, -0.3020, -0.3020,  ..., -0.1059, -0.0824, -0.0588],
           ...,
           [ 0.0588,  0.0588,  0.0588,  ...,  0.3412,  0.3490,  0.3647],
           [ 0.0588,  0.0588,  0.0588,  ...,  0.3490,  0.3490,  0.3647],
           [ 0.0667,  0.0588,  0.0588,  ...,  0.3569,  0.3569,  0.3490]],

          ...,

          [[-0.2627, -0.2706, -0.2706,  ..., -0.0667, -0.0667, -0.0824],
           [-0.2627, -0.2706, -0.2706,  ..., -0.0980, -0.0824, -0.0902],
           [-0.2784, -0.2784, -0.2784,  ..., -0.1216, -0.1137, -0.1216],
           ...,
           [ 0.0667,  0.0588,  0.0588,  ...,  0.3412,  0.3490,  0.3412],
           [ 0.0667,  0.0588,  0.0588,  ...,  0.3490,  0.3490,  0.3412],
           [ 0.0745,  0.0667,  0.0667,  ...,  0.3490,  0.3490,  0.3333]],

          [[-0.2627, -0.2706, -0.2706,  ..., -0.1137, -0.1216, -0.0902],
           [-0.2627, -0.2706, -0.2706,  ..., -0.1294, -0.1294, -0.1137],
           [-0.2706, -0.2863, -0.2863,  ..., -0.1529, -0.1373, -0.1294],
           ...,
           [ 0.0588,  0.0588,  0.0588,  ...,  0.3412,  0.3490,  0.3412],
           [ 0.0588,  0.0588,  0.0588,  ...,  0.3490,  0.3490,  0.3412],
           [ 0.0667,  0.0588,  0.0588,  ...,  0.3490,  0.3490,  0.3333]],

          [[-0.2627, -0.2706, -0.2706,  ..., -0.1843, -0.1529, -0.1059],
           [-0.2627, -0.2706, -0.2706,  ..., -0.1843, -0.1608, -0.1059],
           [-0.2706, -0.2863, -0.2863,  ..., -0.2078, -0.1843, -0.1137],
           ...,
           [ 0.0588,  0.0588,  0.0588,  ...,  0.3333,  0.3412,  0.3490],
           [ 0.0588,  0.0588,  0.0588,  ...,  0.3412,  0.3412,  0.3490],
           [ 0.0667,  0.0588,  0.0588,  ...,  0.3412,  0.3412,  0.3412]]],

         [[[-0.3804, -0.3804, -0.3804,  ...,  0.0902,  0.0824,  0.0824],
           [-0.3725, -0.3882, -0.3882,  ...,  0.0745,  0.0588,  0.0431],
           [-0.3882, -0.4118, -0.4118,  ...,  0.0039, -0.0118,  0.0039],
           ...,
           [ 0.0118,  0.0196,  0.0196,  ...,  0.3255,  0.3333,  0.3569],
           [ 0.0118,  0.0196,  0.0196,  ...,  0.3255,  0.3333,  0.3569],
           [ 0.0196,  0.0196,  0.0196,  ...,  0.3333,  0.3333,  0.3333]],

          [[-0.3804, -0.3882, -0.3882,  ..., -0.0745, -0.0667, -0.0275],
           [-0.3804, -0.3961, -0.3961,  ..., -0.0745, -0.0667, -0.0431],
           [-0.4039, -0.4118, -0.4118,  ..., -0.0824, -0.0588, -0.0510],
           ...,
           [ 0.0039,  0.0196,  0.0196,  ...,  0.3255,  0.3333,  0.3569],
           [ 0.0039,  0.0196,  0.0196,  ...,  0.3255,  0.3333,  0.3569],
           [ 0.0118,  0.0196,  0.0196,  ...,  0.3333,  0.3333,  0.3412]],

          [[-0.3804, -0.3882, -0.3882,  ..., -0.0196, -0.0118,  0.0039],
           [-0.3882, -0.3961, -0.3961,  ..., -0.0353, -0.0275, -0.0039],
           [-0.4118, -0.4118, -0.4118,  ..., -0.0588, -0.0353, -0.0118],
           ...,
           [ 0.0039,  0.0196,  0.0196,  ...,  0.3333,  0.3412,  0.3569],
           [ 0.0039,  0.0196,  0.0196,  ...,  0.3412,  0.3412,  0.3569],
           [ 0.0118,  0.0196,  0.0196,  ...,  0.3490,  0.3490,  0.3412]],

          ...,

          [[-0.3882, -0.3882, -0.3882,  ..., -0.0510, -0.0431, -0.0353],
           [-0.3882, -0.3882, -0.3882,  ..., -0.0824, -0.0667, -0.0510],
           [-0.4039, -0.3961, -0.3961,  ..., -0.1137, -0.0980, -0.0824],
           ...,
           [ 0.0118,  0.0196,  0.0196,  ...,  0.3333,  0.3412,  0.3333],
           [ 0.0118,  0.0196,  0.0196,  ...,  0.3412,  0.3412,  0.3333],
           [ 0.0196,  0.0275,  0.0275,  ...,  0.3412,  0.3412,  0.3255]],

          [[-0.3882, -0.3882, -0.3882,  ..., -0.0745, -0.0824, -0.0431],
           [-0.3882, -0.3882, -0.3882,  ..., -0.0902, -0.0902, -0.0667],
           [-0.3961, -0.4039, -0.4039,  ..., -0.1137, -0.0980, -0.0824],
           ...,
           [ 0.0039,  0.0196,  0.0196,  ...,  0.3333,  0.3412,  0.3333],
           [ 0.0039,  0.0196,  0.0196,  ...,  0.3412,  0.3412,  0.3333],
           [ 0.0118,  0.0196,  0.0196,  ...,  0.3412,  0.3412,  0.3255]],

          [[-0.3882, -0.3882, -0.3882,  ..., -0.1529, -0.1216, -0.0588],
           [-0.3882, -0.3882, -0.3882,  ..., -0.1529, -0.1294, -0.0588],
           [-0.3961, -0.4039, -0.4039,  ..., -0.1765, -0.1529, -0.0667],
           ...,
           [ 0.0039,  0.0196,  0.0196,  ...,  0.3490,  0.3569,  0.3412],
           [ 0.0039,  0.0196,  0.0196,  ...,  0.3569,  0.3569,  0.3412],
           [ 0.0118,  0.0196,  0.0196,  ...,  0.3569,  0.3569,  0.3333]]]]])

**Comment by yaohungt** [comment]
It is just normalization:

transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])

We normalize the images to have mean=0.5 and std=0.5. So the negative value is possible.

**Comment by 321hallelujah** [comment]
got it ,thanks for your reply :)
