### ISSUE TITLE
More of a question

### ISSUE THREAD

**Issue by JulesAM** [yaohungt/Gated-Spatio-Temporal-Energy-Graph#9]
is there any way to run the code with half or 1/4 the charades_v1_rgb dataset ?

**Comment by yaohungt** [comment]
You can modify

https://github.com/yaohungt/Gated-Spatio-Temporal-Energy-Graph/blob/master/datasets/charades.py

to run only 1/4 of Charades.

**Comment by JulesAM** [comment]
Just to be sure: setting 1/4 of all values of  
(1) transforms.resize() input args i.e. 256/224 
(2) transform.normalize
(3) self.s, self.o, self.v 
right ?
